### ISSUE TITLE
De and Re compiled a game, then after it passed to the other room from main menu it crashed

### ISSUE THREAD

**Issue by NumanSadik** [AhmedAhmedEG/VX-Ace-Translator#1]
![image](https://github.com/AhmedAhmedEG/VX-Ace-Translator/assets/68291382/ffa83207-2269-40af-8372-a39e5e2a81f2)
here is a screenshot of the warning, if i click on ok it closes the game could you give me a tip on how to fix this?

**Comment by NumanSadik** [comment]
![image](https://github.com/AhmedAhmedEG/VX-Ace-Translator/assets/68291382/949b3576-3eca-44b7-b009-3338ab727750)
i guess it only affects to some rooms, i've loaded up my save file and some rooms worked just fine while one of them still managed to crash

**Comment by AhmedAhmedEG** [comment]
Then we need to locate the map file that causes this, probably the compiler messed up a map file, If you can share a copy of the game, I can help you, but I suspect this problem is from the script files.

**Comment by AhmedAhmedEG** [comment]
If you can share a copy of the game, I can help you

**Comment by NumanSadik** [comment]
https://transfer.sh/RMuFHLEUgi/Hello%20Charlotte%20EP1.7z
here is the game, it's also free on steam. oh and the beginning text changes after the compression

**Comment by NumanSadik** [comment]
I compared them and find out that these files have been changed from the original:
Classes.rvdata2
CommonEvents.rvdata2
Enemies.rvdata2
Items.rvdata2
and i guess the map files there are too
Scripts.rvdata2
System.rvdata2

and the unchanged files are:
Actors.rvdata2
Skills.rvdata2
States.rvdata2
Troops.rvdata2

**Comment by AhmedAhmedEG** [comment]
ok, i will check it out

**Comment by AhmedAhmedEG** [comment]
Turns out the problem is in the Common Event file only, you have done bytes comparison on the files, but RPG Maker ACE uses a very old ruby version, so there's slight changes in marshaling, so you will find slight differences in the files but they do no harm, the right way to check for changes is decompiling, then compiling from the decompiled files, place the new compiled file in game folder, and decompile again, now you have two decompiled folders, compare them, this will let you know what's missing.

Also scripts files got harmed, I am will checking this out.

**Comment by AhmedAhmedEG** [comment]
Ok, I fixed the CommonEvent problem, the regex was capturing a single digit, this is a mistake as I used \w+ rather than \D+, now let's look into the scripts problem.

**Comment by AhmedAhmedEG** [comment]
Ok, I totally fixed all the bugs, now the game stopped producing errors, I also noticed that I forgot to implement the armors.rvdata2 and weapons.rvdata2 translators, so I will implement them now and release them along with the bug fixes.

**Comment by AhmedAhmedEG** [comment]
Ok, I totally fixed all the bugs, now the game stopped producing errors, I will release the new version in a couple of minutes.
