### ISSUE TITLE
Does not compile certain scripts

### ISSUE THREAD

**Issue by NumanSadik** [AhmedAhmedEG/VX-Ace-Translator#2]
Hello, it's me again, so i've been trying to compile a script called 78 - Window_NameInput.rb but i can't seem to find it logging on the console and whenever i tried to load the game, it gave me an error or typo? in the script that does not seem to exist
![image](https://github.com/AhmedAhmedEG/VX-Ace-Translator/assets/68291382/52be7ee7-1f88-4fda-98c5-0f50697557f3)

**Comment by NumanSadik** [comment]
oh wait, it is not supposed to log that my bad but i really have the error and i do not know why
![image](https://github.com/AhmedAhmedEG/VX-Ace-Translator/assets/68291382/e7f7fc94-1ecf-4265-875b-59b699f2cc45)
![image](https://github.com/AhmedAhmedEG/VX-Ace-Translator/assets/68291382/4034daab-ebe3-47d9-819f-8f861e92d0f2)

**Comment by NumanSadik** [comment]
there is a dot between 'N', and 'O' for some reason

**Comment by AhmedAhmedEG** [comment]
When you got that error? I started the game before and it worked fine

**Comment by AhmedAhmedEG** [comment]
Actually, the compiler never modifies the scripts, maybe ruby converted some characters to wrongs symbols while converting to strings.

**Comment by NumanSadik** [comment]
> When you got that error? I started the game before and it worked fine

I have updated the array and only after that, the game did not boot up, i wonder if i did a wrong in the script but everything seems to be fine, here's the original script and the edited one
![image](https://github.com/AhmedAhmedEG/VX-Ace-Translator/assets/68291382/cc623c2e-6249-42f1-8493-49ca005718b2)
![image](https://github.com/AhmedAhmedEG/VX-Ace-Translator/assets/68291382/830ebe1f-d5e1-44be-bbf1-446fb6372bbf)


I actually once get it done somehow but i don't know how https://media.discordapp.net/attachments/871439679688425492/1130530644087291934/image.png?width=531&height=431

**Comment by NumanSadik** [comment]
oh wait, i think i fixed it, thank you and i am sorry if i did disturb you

**Comment by AhmedAhmedEG** [comment]
Don't worry you can open as much issues as you want, I will never get disrupted, So what was the problem? is it related to my code or other reason?

**Comment by NumanSadik** [comment]
No no, it was just me, there was a similiar array in a different script file that i have completely forgotten about
