### ISSUE TITLE
I found a Scripts.rvdata2 and encountered an error during decryption.

### ISSUE THREAD

**Issue by daiaji** [AhmedAhmedEG/VX-Ace-Translator#3]
[Data.zip](https://github.com/AhmedAhmedEG/VX-Ace-Translator/files/15045164/Data.zip)
```
Decompiling Scripts.rvdata2...Traceback (most recent call last):
        9: from C:/Users/ADMINI~1/AppData/Local/Temp/ocrF5FF.tmp/src/VXAceTranslator.rb:63:in `<main>'
        8: from C:/Users/ADMINI~1/AppData/Local/Temp/ocrF5FF.tmp/src/Modules/RVData2Decompiler.rb:26:in `decompile'
        7: from C:/Users/ADMINI~1/AppData/Local/Temp/ocrF5FF.tmp/src/Modules/RVData2Decompiler.rb:26:in `foreach'
        6: from C:/Users/ADMINI~1/AppData/Local/Temp/ocrF5FF.tmp/src/Modules/RVData2Decompiler.rb:67:in `block in decompile'
        5: from C:/Users/ADMINI~1/AppData/Local/Temp/ocrF5FF.tmp/src/Modules/RVData2Decompiler.rb:361:in `decompile_scripts'
        4: from C:/Users/ADMINI~1/AppData/Local/Temp/ocrF5FF.tmp/src/Modules/RVData2Decompiler.rb:361:in `each_with_index'
        3: from C:/Users/ADMINI~1/AppData/Local/Temp/ocrF5FF.tmp/src/Modules/RVData2Decompiler.rb:361:in `each'
        2: from C:/Users/ADMINI~1/AppData/Local/Temp/ocrF5FF.tmp/src/Modules/RVData2Decompiler.rb:366:in `block in decompile_scripts'
        1: from C:/Users/ADMINI~1/AppData/Local/Temp/ocrF5FF.tmp/src/Modules/RVData2Decompiler.rb:366:in `open'
C:/Users/ADMINI~1/AppData/Local/Temp/ocrF5FF.tmp/src/Modules/RVData2Decompiler.rb:366:in `initialize': Invalid argument @ rb_sysopen - D:/456/Scripts/./121 - 画面拡大640*480.rb (Errno::EINVAL)
```
It seems that Scripts.rvdata2 still calls wfcrypt.dll, while Scripts.rvdata2_o does not.

**Comment by AhmedAhmedEG** [comment]
Sorry for late replay, seems like that Script.rvdata2 have a directory with a . in it, this surly will cause errors with file system, let me check that.

**Comment by AhmedAhmedEG** [comment]
Ok, the problem is the astrik (*) in the file name, Windows doesn't accept them in filenames, I will add a filename filter to removed illigal characters from script names.

**Comment by AhmedAhmedEG** [comment]
I have fixed the problem, I added a filter to remove illegal characters from script file names, using this regex:-
[<>:"\/\\|?*]

**Comment by daiaji** [comment]
Okay, I'll go back and try updating.

**Comment by daiaji** [comment]
Is it available on Linux?

**Comment by AhmedAhmedEG** [comment]
> Is it available on Linux?

You have the raw ruby scripts there, you can go ahead and install the version of Ruby mentioned in the readme and manually run the scripts, I only offer packed versions for Windows.

**Comment by daiaji** [comment]
I compiled and decompiled rvdata2 on Linux and it worked without any glitches.

**Comment by AhmedAhmedEG** [comment]
> I compiled and decompiled rvdata2 on Linux and it worked without any glitches.

This is very nice!
